import Head from 'next/head';

import { useCompanies } from '../services/companies/index';
import {
  Header,
  Container,
  Footer,
  KPIs,
  Sort,
  Table,
  Filter,
  ShowCritical,
} from '../components/';

export default function Dashboard() {
  const { data, loading } = useCompanies();
  return (
    <>
      <Head>
        <title>Gronda Dashboard</title>
        <meta name="Gronda Dashboard" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <div>
          <Filter loading={loading} />
          <KPIs
            loading={loading}
            activeSource={data?.activeSource}
            nps={data?.nps}
            weeklyActive={data?.weeklyActive}
          />
        </div>
        <div>
          <ShowCritical />
          <Sort />
          <Table loading={loading} companies={data?.companies} />
        </div>
      </Container>
      <Footer />
    </>
  );
}
