import Head from 'next/head';

import { useCompanies } from '../services/companies/index';
import {
  Header,
  Container,
  Footer,
  KPIs,
  Sort,
  Table,
  Filter,
  ShowCritical,
} from '../components/';

export default function Dashboard() {
  const { data, loading } = useCompanies();
  return (
    <>
      <Head>
        <title>Gronda Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Filter />
        <KPIs />
        <ShowCritical />
        <Sort />
        <Table />
      </Container>
      <Footer />
    </>
  );
}
