import Head from 'next/head';
import { useState } from 'react';

import { KPIs, Table, Dropdown, ShowCritical } from '../components/';
import { Header, Container, Footer, Section } from '../shared/layout';

import { useCompanies } from '../services/companies/index';
import { sortItems, filterItems } from '../graphql/types';

export default function Dashboard() {
  const [filterState, setfilterState] = useState(filterItems[0]);
  const [sortState, setSortState] = useState(sortItems[0]);
  const [showCritical, setShowCritical] = useState(false);
  const { data, loading } = useCompanies(filterState?.payload);

  return (
    <>
      <Head>
        <title>Gronda Dashboard</title>
        <meta name="Gronda Dashboard" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Dropdown
          label={'Filter By'}
          setState={(item) => {
            setfilterState(item);
            setSortState(sortItems[0]);
          }}
          items={filterItems}
          value={filterState}
        />
        <KPIs
          loading={loading}
          activeSource={data?.activeSource}
          nps={data?.nps}
          weeklyActive={data?.weeklyActive}
        />
        <Section>
          <ShowCritical setState={setShowCritical} />
          <Dropdown
            label={'Sort By'}
            setState={setSortState}
            items={sortItems}
            value={sortState}
          />
        </Section>
        <Table
          loading={loading}
          companies={data?.companies}
          sortState={sortState}
          showCritical={showCritical}
        />
      </Container>
      <Footer />
    </>
  );
}
